[[channels]]
admin = 'forsenCD'
channel = 'pepega'

[global]
auth_host = 'localhost'
auth_port = 8099

[database] # PostgreSQL
host = "localhost"
port = 5432
username = 'develbot'
password = 'develbot'
database = "develbot"

[twitch]
bot_name = "cool_bot_name"
client_id = "blah-blah-blah"
client_secret = "blah-blah-blah"
check_every_sec = 15
