# log4rs configuration file
# You can find more robust example at https://docs.rs/log4rs/1.0.0/log4rs/#configuration-via-a-yaml-file

# Scan this file for changes every 30 seconds
refresh_rate = "30 seconds"

# An appender named "stdout" that writes to stdout
[appenders.stdout]
kind = "console"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
[root]
appenders = ["stdout"]
level = "debug"
